# Generated by Django 6.0.3 on 2026-05-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "completada",
                    models.BooleanField(
                        default=False,
                        help_text="La tarea esta completada?",
                        verbose_name="Tarea finalizada",
                    ),
                ),
                ("fecha_completado", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="La tarea esta activa?"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="card_image/"),
                ),
                (
                    "etiqueta",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="etiqueta",
                        to="todolist.etiqueta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de proyecto",
                "verbose_name_plural": "Tareas de proyecto",
                "ordering": ["-id"],
            },
        ),
    ]
