# Generated by Django 6.0.3 on 2026-04-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_etiqueta_tarea_etiqueta"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="activo",
            field=models.BooleanField(default=True, help_text="La tarea esta activa?"),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="completada",
            field=models.BooleanField(
                default=False,
                help_text="La tarea esta completada?",
                verbose_name="Tarea finalizada",
            ),
        ),
    ]
